In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [4]:
np.array([1,2.0,3,4])

array([1., 2., 3., 4.])

In [6]:
np.array([[1,2,3,4],[5,6,7,8]]) 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
a = np.array([[5,10,15],[20,25,20]]) 
print('Array :','\n',a) 
print('Dimensions :','\n',a.ndim)

Array : 
 [[ 5 10 15]
 [20 25 20]]
Dimensions : 
 2


In [9]:
a = np.array([1,2,3,4,5,6]) 
print(a[1:5:2])

[2 4]


In [10]:
a = np.array([1,2,3,4,5,6]) 
print(a[1:6:2])

[2 4 6]


In [12]:
a = np.array([1,2,3,4,5,6]) 
print(a[:6:2]) 
print(a[1::2]) 
print(a[1:6:])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


In [14]:
import pandas as pd 
data_england = {'Name': ['Kane', 'Sterling', 'Saka', 'Maguire'], 'Age': [27, 26, 19, 28]}
data_italy = {'Name': ['Immobile', 'Insigne', 'Chiellini', 'Chiesa'], 'Age': [31, 30, 36, 23]} 
df_england = pd.DataFrame(data_england) 
df_italy = pd.DataFrame(data_italy)

In [15]:
df_england

Name  Age
0      Kane   27
1  Sterling   26
2      Saka   19
3   Maguire   28

In [16]:
df_italy

Name  Age
0   Immobile   31
1    Insigne   30
2  Chiellini   36
3     Chiesa   23

In [17]:
frames = [df_england, df_italy] 
both_teams = pd.concat(frames) 
both_teams

Name  Age
0       Kane   27
1   Sterling   26
2       Saka   19
3    Maguire   28
0   Immobile   31
1    Insigne   30
2  Chiellini   36
3     Chiesa   23

In [18]:
club = ['Tottenham', 'Man City', 'Arsenal', 'Man Utd'] 
df_england['Associated Clubs'] = club 
df_england

Name  Age Associated Clubs
0      Kane   27        Tottenham
1  Sterling   26         Man City
2      Saka   19          Arsenal
3   Maguire   28          Man Utd